- name: Setup workstation
  hosts: local
  roles:
    - git
    - apt
    - starship
    - role: zsh
      vars_files:
        - roles/zsh/vars/main.yml
    - tmux
    - neofetch
    - zoxide
    - pyenv
    - poetry
    - nvm